services:

  db:
    container_name: iam-core-db
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_USER: iamcore
      POSTGRES_DB: iamcore
      POSTGRES_PASSWORD: iamcore
    volumes:
    - iam-core-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - iam-network
    ports:
      - 9080:5432

  message-broker:
    container_name: iam-message-broker
    image: rabbitmq:3-management-alpine
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - iam-network
    ports:
      - 5672:5672
      - 15672:15672

  keydloak-db:
    container_name: iam-keycloak-db
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_DB: iamkeycloak
      POSTGRES_USER: iamkeycloak
      POSTGRES_PASSWORD: iamkeycloak
    volumes:
    - iam-keycloak-data:/var/lib/postgresql/data
    networks:
      - iam-network
    ports:
      - 9081:5432

  keycloak:
    depends_on:
      - keydloak-db
    container_name: iam-keycloak
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: iamkeycloak
      DB_USER: iamkeycloak
      DB_PASSWORD: iamkeycloak
    image: quay.io/keycloak/keycloak:24.0.3
    restart: always
    command: start-dev
    networks:
      - iam-network
    ports:
      - 8080:8080
 
volumes:
  iam-core-data:
  iam-keycloak-data:

networks:
  iam-network:
