services:

  db:
    container_name: iam-core-db
    image: postgres:16.2-alpine
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: iamcore
      POSTGRES_DB: iamcore
      POSTGRES_PASSWORD: iamcore
    volumes:
    - iam-core-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s

  # app:
  #   container_name: todo-app
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   volumes:
  #     - .:/app
  #   ports:
  #   - "8080:8080"
  #   environment:
  #     DATABASE_URL: postgres://todoapp:todoapp@todo-db:5432/todoapp
  #   depends_on:
  #     db:
  #       condition: service_healthy
 
volumes:
  iam-core-data: